name: Generate Snake Game

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update data
    runs-on: ubuntu-latest
    steps:
      # Ensure the dist directory exists
      - name: Create dist directory
        run: mkdir -p dist

      # Snake Animation
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: A-KumarSharma
          svg_out_path: dist/github-contribution-grid-snake2.svg
          snake_color: 'blue'

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
